# Generated by Django 3.0.8 on 2020-07-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='recipe_image/default_recipe.jpg', upload_to='recipe_image'),
        ),
    ]
