# Generated by Django 3.0.8 on 2020-07-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipecard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeCard',
        ),
    ]
