# Generated by Django 3.0.8 on 2020-07-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=450)),
                ('sender', models.EmailField(max_length=254)),
                ('cc_myself', models.BooleanField()),
            ],
        ),
    ]
