# Generated by Django 3.0.8 on 2020-07-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cc_myself',
            new_name='important',
        ),
    ]
