# Generated by Django 3.0.8 on 2020-07-11 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecpieItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('meal_option', models.CharField(choices=[('HH', 'Heart-Healthy'), ('QE', 'Quick&Easy'), ('LC', 'Low-Calorie'), ('GF', 'Gluten-Free'), ('DA', 'Diabetic'), ('VG', 'Vegetarian')], default='Heart-Healthy', max_length=2)),
                ('description', models.TextField()),
                ('time_required', models.CharField(max_length=30)),
                ('instructions', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recpie.Author')),
            ],
        ),
    ]
