# Generated by Django 3.0.8 on 2020-07-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpie', '0004_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recpieitems',
            name='meal_option',
            field=models.CharField(choices=[('HH', 'Heart-Healthy'), ('QE', 'Quick&Easy'), ('LC', 'Low-Calorie'), ('GF', 'Gluten-Free'), ('DA', 'Diabetic'), ('VG', 'Vegetarian')], default='Heart-Healthy', max_length=2),
        ),
    ]
