# Generated by Django 3.0.8 on 2020-07-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpie', '0005_auto_20200707_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='recpieitems',
            name='measurement',
            field=models.CharField(choices=[('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('c', 'Cup'), ('pt', 'Pint'), ('qt', 'Quart'), ('g', 'Gallon')], default='Teaspoon', max_length=4),
        ),
    ]
