# Generated by Django 3.0.8 on 2020-07-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recpie', '0006_auto_20200707_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recpieitems',
            name='measurement',
        ),
    ]
