# Generated by Django 3.0.8 on 2020-07-09 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recpie', '0007_remove_recpieitems_measurement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
