# Generated by Django 3.0.8 on 2020-07-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default_user.jpg', upload_to='profile_image'),
        ),
    ]
