# Generated by Django 3.0.8 on 2020-07-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200721_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='profile_image/default_user.jpg', upload_to='profile_image'),
        ),
    ]
